- name: Add nginx repository
  yum_repository:
    name: nginx_repo
    description: nginx repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: 0
    enabled: 1
- name: install nginx
  yum: name=nginx state=present
- name: set auto start nginx
  command: chkconfig nginx on
- service:
    name: nginx
    state: restarted
  when: ansible_connection != 'docker'